//go:build linux

package sandbox

import (
	"encoding/json"
	"fmt"

	libseccomp "github.com/seccomp/libseccomp-golang"
)

// seccompProfile mirrors the Docker/libseccomp profile JSON that core
// (internal/sandbox/executor/security) renders into the sandbox image. ghost
// only consumes this file; core is the single source of truth for the policy.
type seccompProfile struct {
	DefaultAction   string           `json:"defaultAction"`
	DefaultErrnoRet *uint            `json:"defaultErrnoRet,omitempty"`
	Architectures   []string         `json:"architectures,omitempty"`
	Syscalls        []seccompSyscall `json:"syscalls,omitempty"`
}

type seccompSyscall struct {
	Names  []string     `json:"names"`
	Action string       `json:"action"`
	Args   []seccompArg `json:"args,omitempty"`
}

type seccompArg struct {
	Index    uint   `json:"index"`
	Value    uint64 `json:"value"`
	ValueTwo uint64 `json:"valueTwo,omitempty"`
	Op       string `json:"op"`
}

// ApplySeccompFromJSON installs the Docker-format seccomp profile (passed inline
// as JSON, generated by core at runtime — single source of truth, no image
// dependency) as a filter on the current process. The filter is inherited
// across fork/execve, so applying it in ghost before the student command runs
// (exec mode: before execve; supervise mode: before fork) covers the command.
// NoNewPrivs is set by Load, composes idempotently with Landlock.
func ApplySeccompFromJSON(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	var p seccompProfile
	if err := json.Unmarshal(data, &p); err != nil {
		return fmt.Errorf("seccomp: parse profile: %w", err)
	}
	filter, err := buildSeccompFilter(&p)
	if err != nil {
		return err
	}
	defer filter.Release()
	if err := filter.SetNoNewPrivsBit(true); err != nil {
		return fmt.Errorf("seccomp: set no_new_privs: %w", err)
	}
	if err := filter.Load(); err != nil {
		return fmt.Errorf("seccomp: load filter: %w", err)
	}
	return nil
}

func buildSeccompFilter(p *seccompProfile) (*libseccomp.ScmpFilter, error) {
	defAct, err := parseAction(p.DefaultAction, p.DefaultErrnoRet)
	if err != nil {
		return nil, err
	}
	filter, err := libseccomp.NewFilter(defAct)
	if err != nil {
		return nil, fmt.Errorf("seccomp: new filter: %w", err)
	}
	for _, a := range p.Architectures {
		arch, err := parseArch(a)
		if err != nil {
			return nil, err
		}
		if err := filter.AddArch(arch); err != nil {
			// Already present or unsupported on this kernel: tolerate rather
			// than fail the whole profile over one arch declaration.
			continue
		}
	}
	for _, sc := range p.Syscalls {
		act, err := parseAction(sc.Action, nil)
		if err != nil {
			return nil, fmt.Errorf("seccomp: action %q: %w", sc.Action, err)
		}
		conds, err := parseConditions(sc.Args)
		if err != nil {
			return nil, err
		}
		for _, name := range sc.Names {
			nr, err := libseccomp.GetSyscallFromName(name)
			if err != nil {
				// Name not present on this arch/kernel (e.g. an x86-only name
				// on arm64). Skip: it cannot be called here, and under
				// default-deny leaving it unlisted keeps it denied (safe).
				continue
			}
			if len(conds) > 0 {
				if err := filter.AddRuleConditional(nr, act, conds); err != nil {
					return nil, fmt.Errorf("seccomp: rule %s (conditional): %w", name, err)
				}
			} else if err := filter.AddRule(nr, act); err != nil {
				return nil, fmt.Errorf("seccomp: rule %s: %w", name, err)
			}
		}
	}
	return filter, nil
}

func parseAction(s string, errnoRet *uint) (libseccomp.ScmpAction, error) {
	switch s {
	case "SCMP_ACT_ALLOW":
		return libseccomp.ActAllow, nil
	case "SCMP_ACT_ERRNO":
		code := int16(1) // EPERM fallback when defaultErrnoRet is absent.
		if errnoRet != nil {
			code = int16(*errnoRet)
		}
		return libseccomp.ActErrno.SetReturnCode(code), nil
	case "SCMP_ACT_KILL_PROCESS":
		return libseccomp.ActKillProcess, nil
	case "SCMP_ACT_KILL_THREAD", "SCMP_ACT_KILL":
		return libseccomp.ActKillThread, nil
	case "SCMP_ACT_TRAP":
		return libseccomp.ActTrap, nil
	case "SCMP_ACT_LOG":
		return libseccomp.ActLog, nil
	default:
		return 0, fmt.Errorf("seccomp: unsupported action %q", s)
	}
}

// archMap translates Docker profile arch names to libseccomp-golang consts.
// The two naming schemes diverge for x86_64 (SCMP_ARCH_X86_64 -> ArchAMD64)
// and aarch64 (SCMP_ARCH_AARCH64 -> ArchARM64).
var archMap = map[string]libseccomp.ScmpArch{
	"SCMP_ARCH_X86":      libseccomp.ArchX86,
	"SCMP_ARCH_X86_64":   libseccomp.ArchAMD64,
	"SCMP_ARCH_X32":      libseccomp.ArchX32,
	"SCMP_ARCH_ARM":      libseccomp.ArchARM,
	"SCMP_ARCH_AARCH64":  libseccomp.ArchARM64,
	"SCMP_ARCH_MIPS":     libseccomp.ArchMIPS,
	"SCMP_ARCH_MIPS64":   libseccomp.ArchMIPS64,
	"SCMP_ARCH_MIPSEL":   libseccomp.ArchMIPSEL,
	"SCMP_ARCH_MIPSEL64": libseccomp.ArchMIPSEL64,
	"SCMP_ARCH_PPC":      libseccomp.ArchPPC,
	"SCMP_ARCH_PPC64":    libseccomp.ArchPPC64,
	"SCMP_ARCH_PPC64LE":  libseccomp.ArchPPC64LE,
	"SCMP_ARCH_S390":     libseccomp.ArchS390,
	"SCMP_ARCH_S390X":    libseccomp.ArchS390X,
	"SCMP_ARCH_RISCV64":  libseccomp.ArchRISCV64,
}

func parseArch(s string) (libseccomp.ScmpArch, error) {
	if a, ok := archMap[s]; ok {
		return a, nil
	}
	return 0, fmt.Errorf("seccomp: unsupported arch %q", s)
}

func parseConditions(args []seccompArg) ([]libseccomp.ScmpCondition, error) {
	if len(args) == 0 {
		return nil, nil
	}
	conds := make([]libseccomp.ScmpCondition, 0, len(args))
	for _, a := range args {
		op, err := parseCompareOp(a.Op)
		if err != nil {
			return nil, err
		}
		var c libseccomp.ScmpCondition
		if op == libseccomp.CompareMaskedEqual {
			// CompareMaskedEqual takes (mask, datum): (arg & mask) == datum.
			c, err = libseccomp.MakeCondition(a.Index, op, a.Value, a.ValueTwo)
		} else {
			c, err = libseccomp.MakeCondition(a.Index, op, a.Value)
		}
		if err != nil {
			return nil, fmt.Errorf("seccomp: condition %+v: %w", a, err)
		}
		conds = append(conds, c)
	}
	return conds, nil
}

func parseCompareOp(s string) (libseccomp.ScmpCompareOp, error) {
	switch s {
	case "SCMP_CMP_NE":
		return libseccomp.CompareNotEqual, nil
	case "SCMP_CMP_LT":
		return libseccomp.CompareLess, nil
	case "SCMP_CMP_LE":
		return libseccomp.CompareLessOrEqual, nil
	case "SCMP_CMP_EQ":
		return libseccomp.CompareEqual, nil
	case "SCMP_CMP_GE":
		return libseccomp.CompareGreaterEqual, nil
	case "SCMP_CMP_GT":
		return libseccomp.CompareGreater, nil
	case "SCMP_CMP_MASKED_EQ":
		return libseccomp.CompareMaskedEqual, nil
	default:
		return 0, fmt.Errorf("seccomp: unsupported compare op %q", s)
	}
}
